source "https://rubygems.org"

# GitHub Pages
gem "github-pages", "~> 227", group: :jekyll_plugins

# if you have any plugins, put them here
group :jekyll_plugins do
end

# Windows does not include zoneinfo files, so bundle the tzinfo-data gem
# and associated library.
platforms :mingw, :x64_mingw, :mswin, :jruby do
  gem "tzinfo", "~> 1.2"
  gem "tzinfo-data"
end

# performance-booster for watching directories on Windows
gem "wdm", "~> 0.1.0", :platforms => [:mingw, :x64_mingw, :mswin]

# see Jekyll serve fails on Ruby 3.0
# https://github.com/jekyll/jekyll/issues/8523
gem "webrick", "~> 1.7"