name: docs

on:
  push:
    paths:
      - 'docs/**'

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          cache: 'pip'

      - name: Install dependencies and deploy
        run: |
          python -m pip install --upgrade pip
          pip install mkdocs-material==8.5.11 mkdocs-redirects
          cd docs
          mkdocs gh-deploy --force
